# Data Preprocing

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("E:\data\data_set\mlfirst1.csv")

In [3]:
X=df.iloc[:,:-1].values
y=df.iloc[:,3].values

# Imputation

### Impute
- Transformers for missing value imputation.
- Impute means 👉 fill missing values (NaN) in your dataset.

### SimpleImputer
- Univariate imputer for completing missing values with simple strategies.

- Replace missing values using a descriptive statistic (e.g. mean, median, or most frequent) along each column, or using a constant value.

In [4]:
from sklearn.impute import SimpleImputer

In [5]:
imputer=SimpleImputer()

## Fit()
- "It learns the statistical values (mean/median/mode) from the training data, which will later be used to replace missing values."
- it only calculate the statestical values . not replace

In [6]:
X

array([['Mumbai', 44.0, 72000.0],
       ['Bangalore', 27.0, 48000.0],
       ['Hyderabad', 30.0, 54000.0],
       ['Bangalore', 38.0, 61000.0],
       ['Hyderabad', 40.0, nan],
       ['Mumbai', 35.0, 58000.0],
       ['Bangalore', nan, 52000.0],
       ['Mumbai', 48.0, 79000.0],
       ['Hyderabad', 50.0, 83000.0],
       ['Mumbai', 37.0, 67000.0]], dtype=object)

In [7]:
imputer=imputer.fit(X[:,1:3])

In [8]:
X

array([['Mumbai', 44.0, 72000.0],
       ['Bangalore', 27.0, 48000.0],
       ['Hyderabad', 30.0, 54000.0],
       ['Bangalore', 38.0, 61000.0],
       ['Hyderabad', 40.0, nan],
       ['Mumbai', 35.0, 58000.0],
       ['Bangalore', nan, 52000.0],
       ['Mumbai', 48.0, 79000.0],
       ['Hyderabad', 50.0, 83000.0],
       ['Mumbai', 37.0, 67000.0]], dtype=object)

In [9]:
imputer

,"missing_values missing_values: int, float, str, np.nan, None or pandas.NA, default=np.nanThe placeholder for the missing values. All occurrences of`missing_values` will be imputed. For pandas' dataframes withnullable integer dtypes with missing values, `missing_values`can be set to either `np.nan` or `pd.NA`.",nan
,"strategy strategy: str or Callable, default='mean'The imputation strategy.- If ""mean"", then replace missing values using the mean along each column. Can only be used with numeric data.- If ""median"", then replace missing values using the median along each column. Can only be used with numeric data.- If ""most_frequent"", then replace missing using the most frequent value along each column. Can be used with strings or numeric data. If there is more than one such value, only the smallest is returned.- If ""constant"", then replace missing values with fill_value. Can be used with strings or numeric data.- If an instance of Callable, then replace missing values using the scalar statistic returned by running the callable over a dense 1d array containing non-missing values of each column... versionadded:: 0.20 strategy=""constant"" for fixed value imputation... versionadded:: 1.5 strategy=callable for custom value imputation.",'mean'
,"fill_value fill_value: str or numerical value, default=NoneWhen strategy == ""constant"", `fill_value` is used to replace alloccurrences of missing_values. For string or object data types,`fill_value` must be a string.If `None`, `fill_value` will be 0 when imputing numericaldata and ""missing_value"" for strings or object data types.",None
,"copy copy: bool, default=TrueIf True, a copy of X will be created. If False, imputation willbe done in-place whenever possible. Note that, in the following cases,a new copy will always be made, even if `copy=False`:- If `X` is not an array of floating values;- If `X` is encoded as a CSR matrix;- If `add_indicator=True`.",True
,"add_indicator add_indicator: bool, default=FalseIf True, a :class:`MissingIndicator` transform will stack onto outputof the imputer's transform. This allows a predictive estimatorto account for missingness despite imputation. If a feature has nomissing values at fit/train time, the feature won't appear onthe missing indicator even if there are missing values attransform/test time.",False
,"keep_empty_features keep_empty_features: bool, default=FalseIf True, features that consist exclusively of missing values when`fit` is called are returned in results when `transform` is called.The imputed value is always `0` except when `strategy=""constant""`in which case `fill_value` will be used instead... versionadded:: 1.2",False


## Transform()
- "It replaces missing values using the statistics learned during the fit stage."
-  fill the missing value in transform 
- with bydefault mean strategy
- The imputer has already learned the mean/median/mode.

In [10]:
X[:,1:3]=imputer.transform(X[:,1:3])

In [11]:
X

array([['Mumbai', 44.0, 72000.0],
       ['Bangalore', 27.0, 48000.0],
       ['Hyderabad', 30.0, 54000.0],
       ['Bangalore', 38.0, 61000.0],
       ['Hyderabad', 40.0, 63777.77777777778],
       ['Mumbai', 35.0, 58000.0],
       ['Bangalore', 38.77777777777778, 52000.0],
       ['Mumbai', 48.0, 79000.0],
       ['Hyderabad', 50.0, 83000.0],
       ['Mumbai', 37.0, 67000.0]], dtype=object)

## Mediaan Strategy

In [12]:
imputer1=SimpleImputer( missing_values='nan',strategy="median")
imputer1=imputer.fit(X[:,1:3])
imputer1

,"missing_values missing_values: int, float, str, np.nan, None or pandas.NA, default=np.nanThe placeholder for the missing values. All occurrences of`missing_values` will be imputed. For pandas' dataframes withnullable integer dtypes with missing values, `missing_values`can be set to either `np.nan` or `pd.NA`.",nan
,"strategy strategy: str or Callable, default='mean'The imputation strategy.- If ""mean"", then replace missing values using the mean along each column. Can only be used with numeric data.- If ""median"", then replace missing values using the median along each column. Can only be used with numeric data.- If ""most_frequent"", then replace missing using the most frequent value along each column. Can be used with strings or numeric data. If there is more than one such value, only the smallest is returned.- If ""constant"", then replace missing values with fill_value. Can be used with strings or numeric data.- If an instance of Callable, then replace missing values using the scalar statistic returned by running the callable over a dense 1d array containing non-missing values of each column... versionadded:: 0.20 strategy=""constant"" for fixed value imputation... versionadded:: 1.5 strategy=callable for custom value imputation.",'mean'
,"fill_value fill_value: str or numerical value, default=NoneWhen strategy == ""constant"", `fill_value` is used to replace alloccurrences of missing_values. For string or object data types,`fill_value` must be a string.If `None`, `fill_value` will be 0 when imputing numericaldata and ""missing_value"" for strings or object data types.",None
,"copy copy: bool, default=TrueIf True, a copy of X will be created. If False, imputation willbe done in-place whenever possible. Note that, in the following cases,a new copy will always be made, even if `copy=False`:- If `X` is not an array of floating values;- If `X` is encoded as a CSR matrix;- If `add_indicator=True`.",True
,"add_indicator add_indicator: bool, default=FalseIf True, a :class:`MissingIndicator` transform will stack onto outputof the imputer's transform. This allows a predictive estimatorto account for missingness despite imputation. If a feature has nomissing values at fit/train time, the feature won't appear onthe missing indicator even if there are missing values attransform/test time.",False
,"keep_empty_features keep_empty_features: bool, default=FalseIf True, features that consist exclusively of missing values when`fit` is called are returned in results when `transform` is called.The imputed value is always `0` except when `strategy=""constant""`in which case `fill_value` will be used instead... versionadded:: 1.2",False


In [13]:
X[:,1:3]=imputer.transform(X[:,1:3])
X

array([['Mumbai', 44.0, 72000.0],
       ['Bangalore', 27.0, 48000.0],
       ['Hyderabad', 30.0, 54000.0],
       ['Bangalore', 38.0, 61000.0],
       ['Hyderabad', 40.0, 63777.77777777778],
       ['Mumbai', 35.0, 58000.0],
       ['Bangalore', 38.77777777777778, 52000.0],
       ['Mumbai', 48.0, 79000.0],
       ['Hyderabad', 50.0, 83000.0],
       ['Mumbai', 37.0, 67000.0]], dtype=object)

# Mode Strategy
- If “most_frequent”, then replace missing using the most frequent value along each column.
- Can be used with strings or numeric data. If there is more than one such value, only the smallest is returned.

In [14]:
imputer2=SimpleImputer( missing_values='nan',strategy='most_frequent')

In [15]:
imputer2

,"missing_values missing_values: int, float, str, np.nan, None or pandas.NA, default=np.nanThe placeholder for the missing values. All occurrences of`missing_values` will be imputed. For pandas' dataframes withnullable integer dtypes with missing values, `missing_values`can be set to either `np.nan` or `pd.NA`.",'nan'
,"strategy strategy: str or Callable, default='mean'The imputation strategy.- If ""mean"", then replace missing values using the mean along each column. Can only be used with numeric data.- If ""median"", then replace missing values using the median along each column. Can only be used with numeric data.- If ""most_frequent"", then replace missing using the most frequent value along each column. Can be used with strings or numeric data. If there is more than one such value, only the smallest is returned.- If ""constant"", then replace missing values with fill_value. Can be used with strings or numeric data.- If an instance of Callable, then replace missing values using the scalar statistic returned by running the callable over a dense 1d array containing non-missing values of each column... versionadded:: 0.20 strategy=""constant"" for fixed value imputation... versionadded:: 1.5 strategy=callable for custom value imputation.",'most_frequent'
,"fill_value fill_value: str or numerical value, default=NoneWhen strategy == ""constant"", `fill_value` is used to replace alloccurrences of missing_values. For string or object data types,`fill_value` must be a string.If `None`, `fill_value` will be 0 when imputing numericaldata and ""missing_value"" for strings or object data types.",None
,"copy copy: bool, default=TrueIf True, a copy of X will be created. If False, imputation willbe done in-place whenever possible. Note that, in the following cases,a new copy will always be made, even if `copy=False`:- If `X` is not an array of floating values;- If `X` is encoded as a CSR matrix;- If `add_indicator=True`.",True
,"add_indicator add_indicator: bool, default=FalseIf True, a :class:`MissingIndicator` transform will stack onto outputof the imputer's transform. This allows a predictive estimatorto account for missingness despite imputation. If a feature has nomissing values at fit/train time, the feature won't appear onthe missing indicator even if there are missing values attransform/test time.",False
,"keep_empty_features keep_empty_features: bool, default=FalseIf True, features that consist exclusively of missing values when`fit` is called are returned in results when `transform` is called.The imputed value is always `0` except when `strategy=""constant""`in which case `fill_value` will be used instead... versionadded:: 1.2",False


In [16]:
imputer2=imputer.fit(X[:,1:3])

In [17]:
X[:,1:3]=imputer.transform(X[:,1:3])
X

array([['Mumbai', 44.0, 72000.0],
       ['Bangalore', 27.0, 48000.0],
       ['Hyderabad', 30.0, 54000.0],
       ['Bangalore', 38.0, 61000.0],
       ['Hyderabad', 40.0, 63777.77777777778],
       ['Mumbai', 35.0, 58000.0],
       ['Bangalore', 38.77777777777778, 52000.0],
       ['Mumbai', 48.0, 79000.0],
       ['Hyderabad', 50.0, 83000.0],
       ['Mumbai', 37.0, 67000.0]], dtype=object)

### Impute Categorical value for independent

## labelencoder
- LabelEncoder is a preprocessing technique used in Machine Learning to convert categorical (text) data into numerical labels.

- Machine learning models cannot understand text directly, so we convert categories into numbers.


🔹 Methods Used
    
        - fit() → Learn unique categories
        
        - transform() → Convert categories into numbers
        
        - fit_transform() → Do both in one step
        
        - inverse_transform() → Convert numbers back to original text

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
labelencoder_y=LabelEncoder()
# y=labelencoder_y.fit_transform(y)
labelencoder_y=labelencoder_y.fit(y)
labelencoder_y
y=labelencoder_y.transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# Split the Data

## train_test_split

- train_test_split is a function from scikit-learn used to split your dataset into:

- Training data → Used to train the model

- Testing data → Used to evaluate the model

  #### Parameter Explained

| Parameter         | Meaning                                                    |
| ----------------- | ---------------------------------------------------------- |
| `X`               | Input features                                             |
| `y`               | Target variable                                            |
| `test_size=0.2`   | 20% data for testing                                       |
| `random_state=42` | Fixes randomness (so result is same every run)             |
| `shuffle=True`    | Shuffle data before splitting (default)                    |
| `stratify=y`      | Keeps class proportion same (important for classification) |


In [20]:
from sklearn.model_selection import train_test_split

In [21]:
# spliting data into training and testing part

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [23]:
print(X_train)
print(X_test)

[['Mumbai' 37.0 67000.0]
 ['Bangalore' 27.0 48000.0]
 ['Bangalore' 38.77777777777778 52000.0]
 ['Mumbai' 48.0 79000.0]
 ['Bangalore' 38.0 61000.0]
 ['Mumbai' 44.0 72000.0]
 ['Mumbai' 35.0 58000.0]]
[['Hyderabad' 30.0 54000.0]
 ['Hyderabad' 50.0 83000.0]
 ['Hyderabad' 40.0 63777.77777777778]]


In [24]:
df

,State,Age,Salary,Purchased
0,Mumbai,44.0,72000.0,No
1,Bangalore,27.0,48000.0,Yes
2,Hyderabad,30.0,54000.0,No
3,Bangalore,38.0,61000.0,No
4,Hyderabad,40.0,NaN,Yes
5,Mumbai,35.0,58000.0,Yes
6,Bangalore,NaN,52000.0,No
7,Mumbai,48.0,79000.0,Yes
8,Hyderabad,50.0,83000.0,No
9,Mumbai,37.0,67000.0,Yes


In [25]:
print(y_train)
print(y_test)

[1 1 0 1 0 0 1]
[0 0 1]


In [26]:
from sklearn.preprocessing import StandardScaler
st_sca=StandardScaler()
X_train=st_sca.fit_transform(X_train)
X_test=sc_X.transform(X_test)

ValueError: could not convert string to float: 'Mumbai'