In [ ]:
!pip install nltk

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from nltk.tokenize import word_tokenize
import nltk
from torch.utils.data import Dataset,DataLoader


In [ ]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""


In [ ]:
# Tokenization
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
from nltk.corpus.reader.ycoe import wordpunct_tokenize
# tokenize
tokens=wordpunct_tokenize(document.lower())

In [ ]:
# build vocab
vocab={'<unk>':0}

for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token]=len(vocab)

vocab

{'<unk>': 0,
 'about': 1,
 'the': 2,
 'program': 3,
 'what': 4,
 'is': 5,
 'course': 6,
 'fee': 7,
 'for': 8,
 'data': 9,
 'science': 10,
 'mentorship': 11,
 '(': 12,
 'dsmp': 13,
 '2023': 14,
 ')': 15,
 'follows': 16,
 'a': 17,
 'monthly': 18,
 'subscription': 19,
 'model': 20,
 'where': 21,
 'you': 22,
 'have': 23,
 'to': 24,
 'make': 25,
 'payments': 26,
 'of': 27,
 'rs': 28,
 '799': 29,
 '/': 30,
 'month': 31,
 '.': 32,
 'total': 33,
 'duration': 34,
 '?': 35,
 '7': 36,
 'months': 37,
 'so': 38,
 'becomes': 39,
 '*': 40,
 '=': 41,
 '5600': 42,
 'approx': 43,
 '.)': 44,
 'syllabus': 45,
 'we': 46,
 'will': 47,
 'be': 48,
 'covering': 49,
 'following': 50,
 'modules': 51,
 ':': 52,
 'python': 53,
 'fundamentals': 54,
 'libraries': 55,
 'analysis': 56,
 'sql': 57,
 'maths': 58,
 'machine': 59,
 'learning': 60,
 'ml': 61,
 'algorithms': 62,
 'practical': 63,
 'mlops': 64,
 'case': 65,
 'studies': 66,
 'can': 67,
 'check': 68,
 'detailed': 69,
 'here': 70,
 '-': 71,
 'https': 72,
 '://'

In [ ]:
len(vocab)

297

In [ ]:
input_sentences=document.split('\n')

In [ ]:
def text_to_indices(sentence,vocab):
  numerical_sentence=[]

  for token in sentence:
    if token in vocab:
      numerical_sentence.append(vocab[token])
    else:
      numerical_sentence.append(vocab['<unk>'])

  return numerical_sentence

In [ ]:
input_numerical_sentences = []

for sentence in input_sentences:
  input_numerical_sentences.append(text_to_indices(word_tokenize(sentence.lower()), vocab))


In [ ]:
len(input_numerical_sentences)

78

In [ ]:
training_sequence=[]

for sentence in input_numerical_sentences:

  for i in range(1,len(sentence)):
    training_sequence.append(sentence[:i+1])

In [ ]:
len(training_sequence)

942

In [ ]:
training_sequence[:5]

[[1, 2], [1, 2, 3], [4, 5], [4, 5, 2], [4, 5, 2, 6]]

In [ ]:
len_list=[]

for sequence in training_sequence:
  len_list.append(len(sequence))

max(len_list)

62

In [ ]:
training_sequence[0]

[1, 2]

In [ ]:
padded_training_sequence = []
for sequence in training_sequence:

  padded_training_sequence.append([0]*(max(len_list) - len(sequence)) + sequence)

In [ ]:
len(padded_training_sequence[10])

62

In [ ]:
padded_training_sequence=torch.tensor(padded_training_sequence)

In [ ]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   0,   4,   5],
        ...,
        [  0,   0,   0,  ..., 293, 188, 294],
        [  0,   0,   0,  ..., 188, 294, 295],
        [  0,   0,   0,  ..., 294, 295, 296]])

In [ ]:
X = padded_training_sequence[:, :-1]
y = padded_training_sequence[:,-1]

In [ ]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   0,   0,   4],
        ...,
        [  0,   0,   0,  ...,   0, 293, 188],
        [  0,   0,   0,  ..., 293, 188, 294],
        [  0,   0,   0,  ..., 188, 294, 295]])

In [ ]:
y

tensor([  2,   3,   5,   2,   6,   7,   8,   9,  10,  11,   3,  12,  13,  14,
         15,   6,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  18,  26,
         27,  28,   0,  32,   5,   2,  33,  34,  27,   2,   6,  35,  33,  34,
         27,   2,   6,   5,  36,  37,  32,  38,   2,  33,   6,   7,  39,  29,
         40,  36,  41,  28,  42,  12,  43,  32,  15,   5,   2,  45,  27,   2,
         11,   3,  35,  47,  48,  49,   2,  50,  51,  52,  54,  55,   8,   9,
         10,  56,   8,   9,  10,   8,  59,  60,  62,  61,  66,  67,  68,   2,
         69,  45,  70,  71,  72,  52,   0,  79,  60,  80,  81,  48,  17,  82,
         27,  83,   3,  35,  85,  81,  80,  79,  60,  86,  87,  88,  17,  82,
         27,  83,   3,  89,  90,  91,  32,  92,  93,  94,  17,  95,  96,  35,
         47,  93,  97,  17,  98,  27,   2,  96,  35, 100, 101, 102,  87, 103,
         85,  38, 104,  92,  22,  94,  17,  96,  22,  67, 105, 106,  80, 107,
          2,  98,  32,  67,  93, 108,   2, 109, 110,  35,  83, 1

In [ ]:
class CustomDataset(Dataset):

  def __init__(self,X,y):
    self.X=X
    self.y=y
  def __len__(self):
    return len(self.X)

  def __getitem__(self,index):
    return self.X[index],self.y[index]

In [ ]:
dataset=CustomDataset(X,y)

In [ ]:
len(dataset)

942

In [ ]:
dataloader=DataLoader(dataset,batch_size=32,shuffle=True)

In [ ]:
class LSTMModel(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding=nn.Embedding(vocab_size,100)
    self.lstm=nn.LSTM(100,150,batch_first=True)
    self.fc=nn.Linear(150,vocab_size)

  def forward(self,x):
    embedded=self.embedding(x)
    intermediate_hidden_states,(final_hidden_state,final_cell_state)=self.lstm(embedded)
    return self.fc(final_hidden_state.squeeze(0))

    return output

In [ ]:
model=LSTMModel(len(vocab))


In [ ]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [ ]:
model.to(device)

LSTMModel(
  (embedding): Embedding(297, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=297, bias=True)
)

In [ ]:
from torch.optim import optimizer
epochs=50
learning_rate=0.001

criterion=nn.CrossEntropyLoss()

optimizer=optim.Adam(model.parameters(),lr=learning_rate)

In [ ]:
# training loop

for epoch in range(epochs):
  total_loss=0

  for batch_x,batch_y in dataloader:

    batch_x=batch_x.to(device)
    batch_y=batch_y.to(device)

    optimizer.zero_grad()

    output=model(batch_x)

    loss=criterion(output,batch_y)

    loss.backward()

    optimizer.step()

    total_loss+=loss.item()

  print(f'Epoch {epoch+1}/{epochs}, Loss: {total_loss/len(dataloader)}')

Epoch 1/50, Loss: 5.521949084599813
Epoch 2/50, Loss: 4.855675093332926
Epoch 3/50, Loss: 4.4379706939061485
Epoch 4/50, Loss: 4.03359235127767
Epoch 5/50, Loss: 3.670247546831767
Epoch 6/50, Loss: 3.2898842334747314
Epoch 7/50, Loss: 2.9535491387049357
Epoch 8/50, Loss: 2.6220133622487385
Epoch 9/50, Loss: 2.329360286394755
Epoch 10/50, Loss: 2.0589402039845783
Epoch 11/50, Loss: 1.8164191206296285
Epoch 12/50, Loss: 1.603769099712372
Epoch 13/50, Loss: 1.3996623873710632
Epoch 14/50, Loss: 1.2343999147415161
Epoch 15/50, Loss: 1.0848796526590982
Epoch 16/50, Loss: 0.9519823491573334
Epoch 17/50, Loss: 0.8403076827526093
Epoch 18/50, Loss: 0.7467883388201396
Epoch 19/50, Loss: 0.6551354269186656
Epoch 20/50, Loss: 0.5907122294108073
Epoch 21/50, Loss: 0.5346129169066747
Epoch 22/50, Loss: 0.47594343523184457
Epoch 23/50, Loss: 0.4300619716445605
Epoch 24/50, Loss: 0.39503900210062665
Epoch 25/50, Loss: 0.36459727933009467
Epoch 26/50, Loss: 0.33651348352432253
Epoch 27/50, Loss: 0.314

In [ ]:
# prediction

def prediction(model,vocab,text):

  # tokenize
  tokenized_text=word_tokenize(text.lower())

  # text-> numerical indices
  numerical_text=text_to_indices(tokenized_text,vocab)

  # padding
  padded_text=torch.tensor([0]*(61-len(numerical_text))+numerical_text,dtype=torch.long).unsqueeze(0)

  # send to model
  output=model(padded_text)

  # predicted index
  value,index=torch.max(output,dim=1)

  # merge with text
  return text +" "+list(vocab.keys())[index]

In [ ]:
prediction(model,vocab,'The course follows a monthly')

'The course follows a monthly subscription'

In [ ]:
import time

num_tokens=10
input_text='hi how are'

for i in range(num_tokens):
  output_text=prediction(model,vocab,input_text)
  print(output_text)
  input_text=output_text
  time.sleep(1)

hi how are ,
hi how are , i
hi how are , i be
hi how are , i be informed
hi how are , i be informed about
hi how are , i be informed about the
hi how are , i be informed about the upcoming
hi how are , i be informed about the upcoming class
hi how are , i be informed about the upcoming class ?
hi how are , i be informed about the upcoming class ? ?


In [ ]:
dataloader1=DataLoader(dataset,batch_size=32,shuffle=True)


In [ ]:
# Function to calculate accuracy
def calculate_accuracy(model,dataloader,device):
  model.eval()
  correct=0
  total=0

  with torch.no_grad():

    for batch_x,batch_y in dataloader1:
      batch_x,batch_y=batch_x.to(device),batch_y.to(device)

      output=model(batch_x)

      _,predicted=torch.max(output,dim=1)

      total+=batch_y.size(0)

      correct+=(predicted==batch_y).sum().item()

  accuracy=correct/total*100
  return accuracy
#  compute accuracy
accuracy=calculate_accuracy(model,dataloader,device)
print(f'Accuracy: {accuracy:.2f}%')

Accuracy: 95.75%
