In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


# train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# Scalling

In [7]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [8]:
X_train

array([[ 0.05748307,  0.54331151,  0.08814543, ...,  0.44235744,
         1.06386501,  0.89813173],
       [-0.74751627,  0.23107588, -0.57296568, ...,  2.13451843,
         5.90167228,  4.74938208],
       [-0.83000737,  0.71107991, -0.82381718, ..., -0.76630756,
         0.39384379, -0.23572801],
       ...,
       [ 0.85679338,  0.37554311,  0.83658087, ...,  1.01241167,
        -0.47305571, -0.46863184],
       [-1.27460595, -0.81048627, -1.28844854, ..., -0.64494601,
        -0.26030016, -0.15719693],
       [-0.84422997, -1.09010027, -0.87654131, ..., -1.08238763,
        -1.61780761, -0.6224667 ]], shape=(455, 30))

In [9]:
y_train

36     M
3      M
551    B
481    B
313    B
      ..
340    B
73     M
335    M
234    B
173    B
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
y_train

array([1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,

# Numpy array to PyTorch tensors

In [14]:
X_train_tensor=torch.from_numpy(X_train.astype(np.float32))
X_test_tensor=torch.from_numpy(X_test.astype(np.float32))
y_train_tensor=torch.from_numpy(y_train.astype(np.float32))
y_test_tensor=torch.from_numpy(y_test.astype(np.float32))

In [16]:
X_test_tensor.shape

torch.Size([114, 30])

In [17]:
y_test_tensor.shape

torch.Size([114])

In [18]:
from torch.utils.data import Dataset,DataLoader

class CustomDataset(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels
    def __len__(self):
        return len(self.features)

    def __getitem__(self,idx):
        return self.features[idx],self.labels[idx]

In [19]:
train_dataset=CustomDataset(X_train_tensor,y_train_tensor)
test_dataset=CustomDataset(X_test,y_test_tensor)

In [20]:
train_dataset[10]

(tensor([ 0.0433,  0.2660,  0.0379, -0.0840, -0.5023,  0.1009, -0.4859, -0.4702,
         -1.1613, -0.4159, -0.2051, -0.3600, -0.0643, -0.1964, -0.9591,  0.3710,
         -0.1420,  0.2596, -0.5323, -0.4044,  0.0574,  0.2402,  0.1623, -0.0744,
         -0.7514,  0.5290, -0.1214,  0.2803, -0.6144, -0.3293]),
 tensor(0.))

In [21]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

# Deffining The Model

In [22]:
import torch.nn as nn

class MySimleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)

        return out

# Important Parameters

In [23]:
learning_rate=0.1
epochs=25

In [25]:
# create model
model=MySimleNN(X_train_tensor.shape[1])

# define optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

# define loss function
loss_function=nn.BCELoss()

# Training Pipeline

In [27]:
# define loop
for epoch in range(epochs):
    for batch_features,batch_labels in train_loader:
        # forward pass
        y_pred=model(batch_features)

        # loss calculate
        loss =loss_function(y_pred,batch_labels.view(-1,1))

        # clear gradients
        optimizer.zero_grad()

        # backward pass
        loss.backward()

        # parameters update
        optimizer.step()
    # print loss in each epoch
    print(f"Epoch:,{epoch+1},loss:{loss.item()}")

Epoch:,1,loss:0.2995927929878235
Epoch:,2,loss:0.19108769297599792
Epoch:,3,loss:0.18961967527866364
Epoch:,4,loss:0.18173035979270935
Epoch:,5,loss:0.08498184382915497
Epoch:,6,loss:0.14491382241249084
Epoch:,7,loss:0.025686977431178093
Epoch:,8,loss:0.09206131845712662
Epoch:,9,loss:0.13581779599189758
Epoch:,10,loss:0.08644165843725204
Epoch:,11,loss:0.06760486215353012
Epoch:,12,loss:0.05262520909309387
Epoch:,13,loss:0.019764887169003487
Epoch:,14,loss:0.04561459645628929
Epoch:,15,loss:0.20851005613803864
Epoch:,16,loss:0.0006353402277454734
Epoch:,17,loss:0.06563785672187805
Epoch:,18,loss:0.1462344229221344
Epoch:,19,loss:0.11787097901105881
Epoch:,20,loss:0.1315954029560089
Epoch:,21,loss:0.0579589381814003
Epoch:,22,loss:0.04017845168709755
Epoch:,23,loss:0.08456259220838547
Epoch:,24,loss:0.3101777136325836
Epoch:,25,loss:0.17505720257759094


# Evaluation

In [29]:
# Model Evaluation using test_loader
model.eval() # set the model of evaluation
accuracy_list=[]

with torch.no_grad():
    # forward pass
    y_pred=model(batch_features)
    y_pred=(y_pred>0.8).float() # convert probability

    # calculate accuracy for the current batch
    batch_accuracy=(y_pred.view(-1)==batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

# calculate overall accuracy
overall_accuracy=sum(accuracy_list)/len(accuracy_list)
print(f"accuracy: {overall_accuracy:.4f}")

accuracy: 0.8571
