In [2]:
import torch
print(torch.__version__)

2.11.0+cpu


In [3]:
if torch.cuda.is_available():
    print('GPU is Available!')
    print(f'Using GPU: {torch.cuda.get_device_name(0)}')
else:
    print('GPU not available .Using CPU')

GPU not available .Using CPU


# Creating A Tensor

In [4]:
# using empty 
a=torch.empty(2,3)

In [5]:
a

tensor([[4.4757e-16, 2.1412e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [6]:
# check type
type(a)

torch.Tensor

In [7]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using rand
torch.rand(2,3)

tensor([[0.1730, 0.9801, 0.0384],
        [0.2372, 0.0016, 0.4640]])

In [10]:
# use of seed
torch.rand(2,3)


tensor([[0.5247, 0.1179, 0.3751],
        [0.7978, 0.6009, 0.8239]])

In [11]:
# manual_Seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
# other ways
# arange
print('using arange ->',torch.arange(0,10,2))

# using linspace
print('using linspace ->',torch.linspace(0,100,10))

# using eye
print('using eye ->',torch.eye(5))

# using full
print('using full ->',torch.full((3,3),5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([  0.0000,  11.1111,  22.2222,  33.3333,  44.4444,  55.5556,  66.6667,
         77.7778,  88.8889, 100.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [21]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
x.shape

torch.Size([2, 3])

In [23]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [25]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

# Tensor Data Types

In [26]:
# find data type
x.dtype

torch.int64

In [27]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [28]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [29]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical operations

# 1.Scalar Operations

In [30]:
x=torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [37]:
# addition
x+2
# substraction
x-2
# multiplication
x*3
# devision
x/3
# int division
(x*100)//3
# mod
((x*100)//3)%2
# power
x**2

tensor([[0.0690, 0.0018],
        [0.0433, 0.0139]])

# 2.Element wise operations

In [39]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)


tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [46]:
# add
a+b
# sub
a-b
#  multiply
a*b
# division
a/b
# power
a**b
# mod
a%b

tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])

In [47]:
c=torch.tensor([1,-2,3,-4])

In [48]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [49]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [50]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [51]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [52]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [53]:
# floar
torch.floor(d)

tensor([1., 2., 3., 4.])

In [54]:
# clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# 3.Reduction Operations

In [55]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [57]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e,dim=0)
# sum along rows
torch.sum(e,dim=1)

tensor([15., 13.])