In [4]:
# Reading the image
import cv2
img=cv2.imread("E:\Photos\horse.jpg")


cv2.imshow('7 horses',img)
cv2.imshow('7 horses',img)
cv2.waitKey(0) # until we don't close else we can give time in miliseconds
# cv2.distroywindow('one window')
# cv2.distroyallwindows('all windows')

-1

# Slideshow the images

In [10]:
import cv2
import numpy as np
img=cv2.imread('E:\Photos\horse.jpg')
re_img=cv2.resize(img,(800,800))
cv2.imshow('7 horse',re_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
v=np.array([[1,2,1,2],[1,2,1,2]])
v

array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

In [12]:
img

array([[[164, 115,  93],
        [163, 115,  91],
        [161, 112,  86],
        ...,
        [162, 124, 112],
        [162, 125, 111],
        [162, 125, 111]],

       [[164, 115,  93],
        [162, 113,  91],
        [160, 113,  86],
        ...,
        [160, 122, 110],
        [160, 122, 110],
        [159, 122, 108]],

       [[164, 114,  94],
        [162, 113,  91],
        [160, 112,  88],
        ...,
        [158, 120, 108],
        [158, 120, 108],
        [158, 120, 108]],

       ...,

       [[ 27,  47,   5],
        [ 26,  46,   4],
        [ 27,  47,   4],
        ...,
        [ 23,  37,  13],
        [ 28,  41,  19],
        [ 19,  34,   7]],

       [[ 27,  47,   5],
        [ 25,  45,   3],
        [ 26,  46,   3],
        ...,
        [ 22,  37,   9],
        [ 18,  30,  10],
        [ 17,  31,   7]],

       [[ 27,  46,   7],
        [ 25,  45,   3],
        [ 26,  46,   3],
        ...,
        [ 14,  29,   1],
        [ 15,  27,   7],
        [ 23,  36,  14]]

In [23]:
import cv2
import numpy as np
img=cv2.imread('E:\Photos\horse.jpg')
re_img=cv2.resize(img,(250,200)) # horizontaly two image
v=np.vstack((re_img,re_img,re_img))
h=np.hstack((re_img,re_img))
multiframe=np.hstack((v,v,v))
cv2.imshow('7 horse',multiframe)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
import cv2
import numpy as np
import os
list_name=os.listdir("E:\Photos")
list_name

['girl.jpg',
 'horse.jpg',
 'Man and horse in stark contrast.png',
 'mohit.jpeg',
 'num.webp',
 'peacock.jpg',
 'ram_photo',
 'WhatsApp Image 2026-01-17 at 10.59.33.jpeg',
 ']elephant.jpg']

In [ ]:
for name in list_name:
    path="E:\\Photos"
    # img_name=path+'\\'+name
    img_name=os.path.join(path, name)
    img=cv2.imread(img_name)
    img=cv2.resize(img,(400,600))
    cv2.imshow('slidshow',img)
    cv2.waitKey(1000)
    # cv2.waitKey(0)
# cv2.destroyAllWindows()

# read & show the image

In [11]:
import cv2

In [12]:
img=cv2.imread("E:\Photos\]elephant.jpg")
img

array([[[192, 160,  95],
        [192, 160,  95],
        [192, 160,  95],
        ...,
        [141,  96,   0],
        [141,  96,   0],
        [140,  95,   0]],

       [[192, 160,  95],
        [192, 160,  95],
        [192, 160,  95],
        ...,
        [141,  96,   0],
        [141,  96,   0],
        [140,  95,   0]],

       [[192, 160,  95],
        [192, 160,  95],
        [192, 160,  95],
        ...,
        [142,  97,   0],
        [141,  96,   0],
        [141,  96,   0]],

       ...,

       [[ 14,  73,  99],
        [  8,  68,  92],
        [  9,  70,  90],
        ...,
        [  4,  20,  32],
        [  2,  13,  21],
        [  2,   9,  12]],

       [[ 10,  66,  95],
        [  9,  66,  91],
        [ 12,  71,  91],
        ...,
        [  4,  20,  32],
        [  2,  13,  21],
        [  2,   9,  12]],

       [[  4,  60,  89],
        [ 10,  67,  92],
        [ 16,  75,  95],
        ...,
        [  4,  20,  32],
        [  2,  13,  21],
        [  2,   9,  12]]

In [13]:
img.shape

(800, 1000, 3)

In [15]:
img=cv2.resize(img,(500,500))
cv2.imshow('hathi',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

array([[[192, 160,  95],
        [192, 160,  95],
        [192, 160,  95],
        ...,
        [141,  96,   0],
        [141,  96,   0],
        [140,  95,   0]],

       [[192, 160,  95],
        [192, 160,  95],
        [192, 160,  95],
        ...,
        [141,  96,   0],
        [141,  96,   0],
        [140,  95,   0]],

       [[192, 160,  95],
        [192, 160,  95],
        [192, 160,  95],
        ...,
        [142,  97,   0],
        [141,  96,   0],
        [141,  96,   0]],

       ...,

       [[ 14,  73,  99],
        [  8,  68,  92],
        [  9,  70,  90],
        ...,
        [  4,  20,  32],
        [  2,  13,  21],
        [  2,   9,  12]],

       [[ 10,  66,  95],
        [  9,  66,  91],
        [ 12,  71,  91],
        ...,
        [  4,  20,  32],
        [  2,  13,  21],
        [  2,   9,  12]],

       [[  4,  60,  89],
        [ 10,  67,  92],
        [ 16,  75,  95],
        ...,
        [  4,  20,  32],
        [  2,  13,  21],
        [  2,   9,  12]]

In [21]:
img=cv2.imread("E:\Photos\]elephant.jpg",2)
img=cv2.resize(img,(500,500))
cv2.imshow('hathi',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Text Over The image

In [13]:
import cv2

img_get = cv2.imread("E:/Photos/horse.jpg")

if img_get is None:
    print("Error: Image not loaded")
else:
    txt = cv2.putText(
        img=img_get,
        text='7 horse',
        org=(30, 80),
        fontFace=cv2.FONT_HERSHEY_DUPLEX,
        fontScale=3,
        color=(0, 0, 255),
        thickness=3,
        lineType=cv2.LINE_8,
        bottomLeftOrigin=False
    )

    txt = cv2.putText(
        img=img_get,
        text='7 horse',
        org=(80, 80),
        fontFace=cv2.FONT_HERSHEY_DUPLEX,
        fontScale=3,
        color=(144, 0, 114),
        thickness=3,
        lineType=cv2.LINE_8,
        bottomLeftOrigin=True
    )


    cv2.imshow('7 horse', txt)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

# Draw Line And Rectangle On Image

In [31]:
import cv2
old_img=cv2.imread("E:\Photos\mohit.jpeg")
old_img=cv2.resize(old_img,(500,700))

new_img=cv2.line(img=old_img,pt1=(170,160),pt2=(350,150),color=(0,255,0),thickness=4,lineType=4)
cv2.imshow('Mohit',new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [52]:
import cv2
old_img=cv2.imread("E:\Photos\mohit.jpeg")
old_img=cv2.resize(old_img,(500,700))
img_txt=cv2.putText(img=old_img,text='Mohit. 2 dino se lapata hai',org=(30,30),fontFace=2,fontScale=1,color=(255,55,2),thickness=2,lineType=16,bottomLeftOrigin=False)
new_img=cv2.rectangle(img=img_txt,pt1=(100,50),pt2=(380,500),color=(0,255,0),thickness=4,lineType=16)
cv2.imshow('Mohit',new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#  Draw a circle or Ellipse


In [25]:
import cv2
old_img=cv2.imread("E:\Photos\mohit.jpeg")
old_img=cv2.resize(old_img,(500,600))

new_img=cv2.circle(img=old_img,center=(200,120),radius=150,color=(0,225,0),thickness=4,lineType=16)
cv2.imshow('mohit',new_img)
cv2.waitKey(0)

-1

# Ellipse

In [15]:
import cv2

# Use raw string (r'') OR double backslashes
old_img = cv2.imread(r'E:\Photos\mohit.jpeg')

# Check if image loaded properly
if old_img is None:
    print("Error: Image not found!")
else:
    old_img = cv2.resize(old_img, (400, 500))

    new_img = cv2.ellipse(
        img=old_img,
        center=(200, 190),
        axes=(120, 160),
        angle=30,
        startAngle=0,
        endAngle=360,
        color=(0, 255, 0),
        thickness=4,   # FIXED spelling
        lineType=cv2.LINE_8
    )

    cv2.imshow('mohit', new_img)
    cv2.waitKey(0)   # FIXED spelling
    cv2.destroyAllWindows()

# Draw Polygons on Image 

In [16]:
import cv2
import numpy as np

In [25]:
old_img = cv2.imread(r'E:\Photos\mohit.jpeg')
old_img=cv2.resize(old_img,(400,400))

new_img=cv2.polylines(img=old_img,pts=[np.array([[150,150],[180,180],[150,200],[300,180],[80,70]])],isClosed=True,color=(0,200,0),thickness=4,lineType=1)
cv2.imshow('mohit',new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

 # "Arithmetic Operations on Images using OpenCV (Addition and Subtraction)"

In [27]:
import cv2

In [40]:
img1=cv2.imread("E:\Photos\mohit.jpeg")
img2=cv2.imread("E:\Photos\girl.jpg")

img1=cv2.resize(img1,(500,500))
img2=cv2.resize(img2,(500,500))

new_img=cv2.addWeighted(img1,0.8,img2,0.8,0.5)

# substract image
new_img=cv2.subtract(img1,img2)

cv2.imshow('mohit',new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

 # "Arithmetic Operations on Images using OpenCV (Bitwise Operations on Binary Images)"

In [45]:
import cv2
img1=cv2.imread("E:\Photos\mohit.jpeg")
img2=cv2.imread("E:\Photos\girl.jpg")

img1=cv2.resize(img1,(500,500))
img2=cv2.resize(img2,(500,500))

new=cv2.bitwise_and(img1,img2)
h=np.hstack((img1,img2,new))
cv2.imshow('mohit',new)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [48]:
import cv2
img1=cv2.imread("E:\Photos\mohit.jpeg")
img2=cv2.imread("E:\Photos\girl.jpg")

img1=cv2.resize(img1,(500,500))
img2=cv2.resize(img2,(500,500))

new=cv2.bitwise_or(img1,img2)
new=cv2.resize(new,(500,500))
h=np.hstack((img1,img2,new))
cv2.imshow('mohit',new)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [49]:
import cv2
img1=cv2.imread("E:\Photos\mohit.jpeg")
img2=cv2.imread("E:\Photos\girl.jpg")

img1=cv2.resize(img1,(500,500))
img2=cv2.resize(img2,(500,500))

new=cv2.bitwise_xor(img1,img2)
h=np.hstack((img1,img2,new))
cv2.imshow('mohit',new)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [50]:
import cv2
img1=cv2.imread("E:\Photos\mohit.jpeg")
img2=cv2.imread("E:\Photos\girl.jpg")

img1=cv2.resize(img1,(500,500))
img2=cv2.resize(img2,(500,500))

new=cv2.bitwise_not(img1,img2)
h=np.hstack((img1,img2,new))
cv2.imshow('mohit',new)
cv2.waitKey(0)
cv2.destroyAllWindows()

 # Edge detection in an Image using OpenCV

In [55]:
import cv2
img1=cv2.imread("E:\Photos\mohit.jpeg")
img1=cv2.resize(img1,(500,500))

new=cv2.Canny(img1,50,50)

cv2.imshow('mohit',new)
# cv2.imshow('mohit',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(img1.shape)
print(new.shape)

(500, 500, 3)
(500, 500)


# Image Scaling, Rotating using OpenCV  

In [68]:
import cv2
import numpy as np
# Fix path using raw string
img1 = cv2.imread(r"E:\Photos\mohit.jpeg")

if img1 is None:
    print("Error: Image not found!")
else:
    img1 = cv2.resize(img1, (500, 500))
    print(img1.shape)

    h, w = img1.shape[:2]

    # FIX: center, angle, scale should be separate arguments
    matrix = cv2.getRotationMatrix2D((w/2, h/2), 180, 1)

    # Apply rotation
    rotated = cv2.warpAffine(img1, matrix, (w, h))
    h=np.hstack((img1,rotated))

    # Show rotated image (not original)
    cv2.imshow('Rotated Image',h)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

(500, 500, 3)


 # Image blurring using OpenCV

In [75]:
import cv2
import numpy as np
# Fix path using raw string
img1 = cv2.imread(r"E:\Photos\mohit.jpeg")
img1 = cv2.resize(img1, (300, 300))

b=cv2.GaussianBlur(img1,(5,5),0)
m=cv2.medianBlur(img1,5)
c=cv2.bilateralFilter(img1,9,75,75)


h=np.hstack((img1,b,m,c))

cv2.imshow('Rotated Image',h)
cv2.waitKey(0)
cv2.destroyAllWindows()

#  imwrite method using OpenCV

In [82]:
import cv2
import numpy as np
# Fix path using raw string
img1 = cv2.imread(r"E:\Photos\mohit.jpeg")
img1 = cv2.resize(img1, (300, 300))

h=np.hstack((img1,img1))
v=np.vstack((h,h))
cv2.imwrite('stacked_img.jpeg',v)
cv2.imshow('mohit',v)
cv2.waitKey(0)
cv2.destroyAllWindows()

# MakeBorder using OpenCV

In [88]:
import cv2
import numpy as np
# Fix path using raw string
img1 = cv2.imread(r"E:\Photos\mohit.jpeg")
img1 = cv2.resize(img1, (340, 340))

copy=cv2.copyMakeBorder(img1,20,20,20,20,cv2.BORDER_CONSTANT,None,value=2)
copy=cv2.resize(copy,(340,340))

copy1=cv2.copyMakeBorder(img1,20,20,20,20,cv2.BORDER_DEFAULT,None,value=2)
copy1=cv2.resize(copy,(340,340))

copy2=cv2.copyMakeBorder(img1,20,20,20,20,cv2.BORDER_REFLECT,None,value=2)
copy2=cv2.resize(copy,(340,340))

h=np.hstack((img1,copy,copy1,copy2))

cv2.imshow('mohit',h)
cv2.waitKey(0)
cv2.destroyAllWindows()

 # Play a video using OpenCV

In [89]:
import cv2

In [92]:
cap=cv2.VideoCapture(r"C:\Users\USER\Videos\Captures\pretrained_model_transformers.ipynb - Colab - Google Chrome 2026-04-24 00-01-00.mp4")

while cap.isOpened():
    r,frame=cap.read()
    if r==True:
        frame=cv2.resize(frame,(600,500))
        cv2.imshow('video',frame)
        if cv2.waitKey(30) & 0xff==ord("p"):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

 # Capture Video from the Camera using OpenCV

In [2]:
import cv2


In [3]:
cap=cv2.VideoCapture(0)
while True:
    r,frame=cap.read()
    if r==True:
        frame=cv2.resize(frame,(500,500))
        cv2.imshow('video',frame)
        if cv2.waitKey(25) & 0xff== ord("p"):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

# Slow and Fast Motion Video 

In [4]:
import cv2


In [11]:
cap=cv2.VideoCapture(r"C:\Users\USER\Videos\Captures\pretrained_model_transformers.ipynb - Colab - Google Chrome 2026-04-24 00-01-00.mp4")

while cap.isOpened():
    rat,frame=cap.read()
    frame=cv2.resize(frame,(500,500))
    if rat==True:
        cv2.imshow('video',frame)
        if cv2.waitKey(10000) & 0xff==ord('p'):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()

# Morphological operations using OpenCV

In [13]:
import cv2
import numpy as np

- Erosion - shrink the channels
- dilation - sparse the channels
- opening - remove the noise
- closing
- gradient -differnce b/w errosion and dilation
- top hat
- black hat

In [22]:
img=cv2.imread("E:\Photos\horse.jpg")
img=cv2.resize(img,(500,500))
m=np.ones((5,5),np.int8)
er=cv2.erode(img,m,iterations=1)
di=cv2.dilate(img,m,iterations=1)

op=cv2.morphologyEx(img,cv2.MORPH_OPEN,m,iterations=1)

cl=cv2.morphologyEx(img,cv2.MORPH_OPEN,m,iterations=1)

gr=cv2.morphologyEx(img,cv2.MORPH_GRADIENT,m,iterations=1)

tp=cv2.morphologyEx(img,cv2.MORPH_TOPHAT,m,iterations=1)

bp=cv2.morphologyEx(img,cv2.MORPH_BLACKHAT,m,iterations=1)

cv2.imshow('image',img)
# cv2.imshow('er',er)
# cv2.imshow('dil',di)
# cv2.imshow('opening',op)
# cv2.imshow('closing',cl)
# cv2.imshow('gradient',gr)
# cv2.imshow('tophat',tp)
cv2.imshow('tophat',bp)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Image Pyramid using OpenCV


In [27]:
import cv2
img=cv2.imread("E:\Photos\mohit.jpeg")
img=cv2.resize(img,(500,500))

cv2.imshow('mohit',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
img=cv2.imread("E:\Photos\mohit.jpeg")
print(img.shape)

new=cv2.pyrDown(img)
print(new.shape)

new1=cv2.pyrDown(new)
print(new1.shape)

new2=cv2.pyrDown(new1)
print(new2.shape)

big_img=cv2.pyrUp(new2)
print(big_img.shape)

# cv2.imshow('original',img)
# cv2.imshow('1 down',new)
# cv2.imshow('2 down',new1)
cv2.imshow('3 down',new2)
cv2.imshow('sparse img',big_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

(1080, 872, 3)
(540, 436, 3)
(270, 218, 3)
(135, 109, 3)
(270, 218, 3)


# Image Translation using OpenCV 

In [30]:
import cv2
import numpy as np

In [31]:
img=cv2.imread("E:\Photos\mohit.jpeg")
img=cv2.resize(img,(500,500))

m=np.float32([[1,0,100],[0,1,50]])
new=cv2.warpAffine(img,m,(500,500))

cv2.imshow('image',img)
cv2.imshow('m',m)
cv2.imshow('new',new)
cv2.waitKey(0)
cv2.destroyAllWindows()

 # Geometric Transformations of Images

 - Transformations
 - Scalling
 - Translation
 - Rotation
1. Affline Transformation
2. Perspective Transformation

# Background subtraction using OpenCV

In [32]:
import cv2

In [36]:
org_v=cv2.VideoCapture(r"C:\Users\USER\Videos\Captures\pretrained_model_transformers.ipynb - Colab - Google Chrome 2026-04-24 00-01-00.mp4")
sub_m=cv2.createBackgroundSubtractorMOG2()
while True:
    r,frame=org_v.read()
    if r==True:
        frame=cv2.resize(frame,(500,700))
        sub_v=sub_m.apply(frame)
        cv2.imshow('video',frame)
        cv2.imshow('sub',sub_v)
        if cv2.waitKey(25) & 0xff==ord('p'):
            break
            
    else:
        break
org_v.release()
cv2.destroyAllWindows()

 # Extract images from video using OpenCV

In [37]:
import cv2

In [42]:
cap=cv2.VideoCapture(r"C:\Users\USER\Videos\Captures\pretrained_model_transformers.ipynb - Colab - Google Chrome 2026-04-24 00-01-00.mp4")
c=0
while True:
    r,frame=cap.read()
    if r==True:
        frame=cv2.resize(frame,(500,500))
        filename=r"C://Users//USER//Videos//Captures//videophoto"+str(c)+".png"
        cv2.imwrite(filename,frame)
        cv2.imshow('video',frame)
        c=c+1
        if cv2.waitKey(25) & 0xff==ord('p'):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

# cvtColor method OpenCV

In [2]:
import cv2

In [ ]:
org=cv2.imread("E:\Photos\mohit.jpeg")
org=cv2.resize(org,(500,500))
new=cv2.cvtColor(org,cv2.COLOR_BGR2GRAY)
# new=cv2.cvtColor(org,cv2.COLOR_BGR2BGR555)
cv2.imshow(' img',org)
cv2.imshow('color',new)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Crop Image using OpenCV Python