In [4]:
# Reading the image
import cv2
img=cv2.imread("E:\Photos\horse.jpg")


cv2.imshow('7 horses',img)
cv2.imshow('7 horses',img)
cv2.waitKey(0) # until we don't close else we can give time in miliseconds
# cv2.distroywindow('one window')
# cv2.distroyallwindows('all windows')

-1

# Slideshow the images

In [10]:
import cv2
import numpy as np
img=cv2.imread('E:\Photos\horse.jpg')
re_img=cv2.resize(img,(800,800))
cv2.imshow('7 horse',re_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
v=np.array([[1,2,1,2],[1,2,1,2]])
v

array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

In [12]:
img

array([[[164, 115,  93],
        [163, 115,  91],
        [161, 112,  86],
        ...,
        [162, 124, 112],
        [162, 125, 111],
        [162, 125, 111]],

       [[164, 115,  93],
        [162, 113,  91],
        [160, 113,  86],
        ...,
        [160, 122, 110],
        [160, 122, 110],
        [159, 122, 108]],

       [[164, 114,  94],
        [162, 113,  91],
        [160, 112,  88],
        ...,
        [158, 120, 108],
        [158, 120, 108],
        [158, 120, 108]],

       ...,

       [[ 27,  47,   5],
        [ 26,  46,   4],
        [ 27,  47,   4],
        ...,
        [ 23,  37,  13],
        [ 28,  41,  19],
        [ 19,  34,   7]],

       [[ 27,  47,   5],
        [ 25,  45,   3],
        [ 26,  46,   3],
        ...,
        [ 22,  37,   9],
        [ 18,  30,  10],
        [ 17,  31,   7]],

       [[ 27,  46,   7],
        [ 25,  45,   3],
        [ 26,  46,   3],
        ...,
        [ 14,  29,   1],
        [ 15,  27,   7],
        [ 23,  36,  14]]

In [23]:
import cv2
import numpy as np
img=cv2.imread('E:\Photos\horse.jpg')
re_img=cv2.resize(img,(250,200)) # horizontaly two image
v=np.vstack((re_img,re_img,re_img))
h=np.hstack((re_img,re_img))
multiframe=np.hstack((v,v,v))
cv2.imshow('7 horse',multiframe)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
import cv2
import numpy as np
import os
list_name=os.listdir("E:\Photos")
list_name

['girl.jpg',
 'horse.jpg',
 'Man and horse in stark contrast.png',
 'mohit.jpeg',
 'num.webp',
 'peacock.jpg',
 'ram_photo',
 'WhatsApp Image 2026-01-17 at 10.59.33.jpeg',
 ']elephant.jpg']

In [ ]:
for name in list_name:
    path="E:\\Photos"
    # img_name=path+'\\'+name
    img_name=os.path.join(path, name)
    img=cv2.imread(img_name)
    img=cv2.resize(img,(400,600))
    cv2.imshow('slidshow',img)
    cv2.waitKey(1000)
    # cv2.waitKey(0)
# cv2.destroyAllWindows()

# read & show the image

In [11]:
import cv2

In [12]:
img=cv2.imread("E:\Photos\]elephant.jpg")
img

array([[[192, 160,  95],
        [192, 160,  95],
        [192, 160,  95],
        ...,
        [141,  96,   0],
        [141,  96,   0],
        [140,  95,   0]],

       [[192, 160,  95],
        [192, 160,  95],
        [192, 160,  95],
        ...,
        [141,  96,   0],
        [141,  96,   0],
        [140,  95,   0]],

       [[192, 160,  95],
        [192, 160,  95],
        [192, 160,  95],
        ...,
        [142,  97,   0],
        [141,  96,   0],
        [141,  96,   0]],

       ...,

       [[ 14,  73,  99],
        [  8,  68,  92],
        [  9,  70,  90],
        ...,
        [  4,  20,  32],
        [  2,  13,  21],
        [  2,   9,  12]],

       [[ 10,  66,  95],
        [  9,  66,  91],
        [ 12,  71,  91],
        ...,
        [  4,  20,  32],
        [  2,  13,  21],
        [  2,   9,  12]],

       [[  4,  60,  89],
        [ 10,  67,  92],
        [ 16,  75,  95],
        ...,
        [  4,  20,  32],
        [  2,  13,  21],
        [  2,   9,  12]]

In [13]:
img.shape

(800, 1000, 3)

In [15]:
img=cv2.resize(img,(500,500))
cv2.imshow('hathi',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

array([[[192, 160,  95],
        [192, 160,  95],
        [192, 160,  95],
        ...,
        [141,  96,   0],
        [141,  96,   0],
        [140,  95,   0]],

       [[192, 160,  95],
        [192, 160,  95],
        [192, 160,  95],
        ...,
        [141,  96,   0],
        [141,  96,   0],
        [140,  95,   0]],

       [[192, 160,  95],
        [192, 160,  95],
        [192, 160,  95],
        ...,
        [142,  97,   0],
        [141,  96,   0],
        [141,  96,   0]],

       ...,

       [[ 14,  73,  99],
        [  8,  68,  92],
        [  9,  70,  90],
        ...,
        [  4,  20,  32],
        [  2,  13,  21],
        [  2,   9,  12]],

       [[ 10,  66,  95],
        [  9,  66,  91],
        [ 12,  71,  91],
        ...,
        [  4,  20,  32],
        [  2,  13,  21],
        [  2,   9,  12]],

       [[  4,  60,  89],
        [ 10,  67,  92],
        [ 16,  75,  95],
        ...,
        [  4,  20,  32],
        [  2,  13,  21],
        [  2,   9,  12]]

In [21]:
img=cv2.imread("E:\Photos\]elephant.jpg",2)
img=cv2.resize(img,(500,500))
cv2.imshow('hathi',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Text Over The image

In [13]:
import cv2

img_get = cv2.imread("E:/Photos/horse.jpg")

if img_get is None:
    print("Error: Image not loaded")
else:
    txt = cv2.putText(
        img=img_get,
        text='7 horse',
        org=(30, 80),
        fontFace=cv2.FONT_HERSHEY_DUPLEX,
        fontScale=3,
        color=(0, 0, 255),
        thickness=3,
        lineType=cv2.LINE_8,
        bottomLeftOrigin=False
    )

    txt = cv2.putText(
        img=img_get,
        text='7 horse',
        org=(80, 80),
        fontFace=cv2.FONT_HERSHEY_DUPLEX,
        fontScale=3,
        color=(144, 0, 114),
        thickness=3,
        lineType=cv2.LINE_8,
        bottomLeftOrigin=True
    )


    cv2.imshow('7 horse', txt)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

# Draw Line And Rectangle On Image

In [31]:
import cv2
old_img=cv2.imread("E:\Photos\mohit.jpeg")
old_img=cv2.resize(old_img,(500,700))

new_img=cv2.line(img=old_img,pt1=(170,160),pt2=(350,150),color=(0,255,0),thickness=4,lineType=4)
cv2.imshow('Mohit',new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [52]:
import cv2
old_img=cv2.imread("E:\Photos\mohit.jpeg")
old_img=cv2.resize(old_img,(500,700))
img_txt=cv2.putText(img=old_img,text='Mohit. 2 dino se lapata hai',org=(30,30),fontFace=2,fontScale=1,color=(255,55,2),thickness=2,lineType=16,bottomLeftOrigin=False)
new_img=cv2.rectangle(img=img_txt,pt1=(100,50),pt2=(380,500),color=(0,255,0),thickness=4,lineType=16)
cv2.imshow('Mohit',new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#  Draw a circle or Ellipse


In [25]:
import cv2
old_img=cv2.imread("E:\Photos\mohit.jpeg")
old_img=cv2.resize(old_img,(500,600))

new_img=cv2.circle(img=old_img,center=(200,120),radius=150,color=(0,225,0),thickness=4,lineType=16)
cv2.imshow('mohit',new_img)
cv2.waitKey(0)

-1

In [27]:
import cv2
old_img=cv2.imread("E:\Photos\mohit.jpeg")
old_img=cv2.resize(old_img,(500,600))

new_img=cv2.ellipse(img=old_img,center=(200,120),radius=150,color=(0,225,0),thickness=4,lineType=16)
cv2.imshow('mohit',new_img)
cv2.waitKey(0)

error: OpenCV(4.13.0) :-1: error: (-5:Bad argument) in function 'ellipse'
> Overload resolution failed:
>  - ellipse() missing required argument 'axes' (pos 3)
>  - ellipse() takes at most 5 keyword arguments (6 given)
>  - ellipse() missing required argument 'axes' (pos 3)
>  - ellipse() takes at most 5 keyword arguments (6 given)
