# Numpy:
 - Numpy is the fundamental package for scientific computing in Python.
    


                                  

# creatig Numpy array

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,321,3,121,32,1]) #1D array

array([  1,   2,   3, 321,   3, 121,  32,   1])

In [4]:
a=np.array([2,3,4,21,131,32]) #vector
print(a)

[  2   3   4  21 131  32]


In [5]:
type(a) 

numpy.ndarray

In [6]:
# 2D array (matrix)
new=np.array([[34,131,21,11],[2,31,12,11]])
print(new)

[[ 34 131  21  11]
 [  2  31  12  11]]


In [7]:
# 3D array (Tensor)
np.array([[1,2,3,1],(1,2,13,1),{1,2,31,12},[1,23,4,4]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

# Array only accept homogenous data type

In [13]:
# 3D array (Tensor)
# np.array({1,2,'r'}) 
np.array([[1,2,3,3],[12,23,13,13],[221,213,123,3211],[121,2212,233,223]])

array([[   1,    2,    3,    3],
       [  12,   23,   13,   13],
       [ 221,  213,  123, 3211],
       [ 121, 2212,  233,  223]])

In [15]:
print(np.array([[1,2,3,3],[12,23,13,13],[221,213,123,3211],[121,2212,'233',223]]))# if i give atleast on estring larg it convert all array into str
np.array([[1,2,3,3],[12,23,13,13],[221,True,123,3211],[121,2212,233,223]]) #if i give bolean value it convert int decimal

[['1' '2' '3' '3']
 ['12' '23' '13' '13']
 ['221' '213' '123' '3211']
 ['121' '2212' '233' '223']]


array([[   1,    2,    3,    3],
       [  12,   23,   13,   13],
       [ 221,    1,  123, 3211],
       [ 121, 2212,  233,  223]])

# dtype
- the desired data -type for the array .if not given then the type will be determined a minimum type required to hold the objects in the sequence

In [16]:
np.array([11,23,12],dtype=float) #float array

array([11., 23., 12.])

In [17]:
np.array([11,232,11,0],dtype=bool) # the boolean values of decimal

array([ True,  True,  True, False])

In [18]:
np.array([11,23,122],dtype=complex) #comlex array with adding j 

array([ 11.+0.j,  23.+0.j, 122.+0.j])

# Numpy Array Vs Python Sequences
- Numpy arrays have a fixed size at creation ,unlike python lists(which can grow dynamically).
changing the size of an ndarray will create a new array and delete the original.

- The elements in a Numpy array are all required to be of the same data type and thus will be the same size in memory

- Numpy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically ,such operations are executed more efficiently and with less code than is possible using Python's built-in sequences.

- A growing plethora of scientific and mathematical Python -based packages ara using Numpy arrays; though these typiocally supports python -sequence input, they convert such input to Numpy arrays prior to processing and they often output Numpy arrays.

# Arange()
- arange can be called with a varying number of positional arguments

In [19]:
np.arange(1,25) # 1 included, 25- last on got excluded

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [20]:
np.arange(1,25,2) # strides--> Alternate numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

# Reshape()
- Both of number products should be equal to number of items present inside the array

In [22]:
np.arange(1,11).reshape(5,2) # first arg is rows 5 second arg columns 2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [23]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Ones & zeros()
- you can initialize the values and create value . ex: in deep learning weight shape

In [26]:
np.ones(3)

array([1., 1., 1.])

In [27]:
np.ones(2,3) # for matrix from method you have to apply 2 tuples

TypeError: Cannot interpret '3' as a data type

In [29]:
np.ones([3,2]),np.ones((3,3))

(array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [31]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# random()
- Return random floats in the half-open interval [0.0, 1.0).

In [32]:
# Another type -->random()
 
np.random.random((4,4))

array([[0.36653438, 0.82688001, 0.14020036, 0.518724  ],
       [0.38233893, 0.62426702, 0.91270586, 0.82432847],
       [0.7414424 , 0.88186798, 0.94110726, 0.92189975],
       [0.45688219, 0.07479453, 0.98247296, 0.7455977 ]])

# linspace()
- It is also called as Linearly space, Linearly seperable in a given range at equal distance it creates points.

In [33]:
np.linspace(-10,10,10) # divide into 10 equal parts

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [35]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

# identity()
- Identity matrix is that diagonal items will be ones and apart from that will be zeros

In [36]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(4) # eye is shortcut

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# Array Attributes
- attributes are the built-in properties of arrays and modules that give you information about their structure or behavior. For arrays (numpy.ndarray).


In [39]:
a1=np.arange(10) # 1D
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a2=np.arange(12,dtype=float).reshape(3,4) # Matrix
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [41]:
a3=np.arange(8).reshape(2,2,2) # 3D -->Tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

 # 1. ndim
 - To findout given arrays numbers of dimensions.

In [42]:
a1.ndim

1

In [43]:
a2.ndim

2

In [44]:
a3.ndim

3

# 2.shape
- gives each item consist of no of rows and no of column

In [45]:
a1.shape #1D array has 10 items

(10,)

In [46]:
a2.shape # 3 rows and 4 columns

(3, 4)

In [47]:
a3.shape

(2, 2, 2)

# 3.size
- gives number of items (rows*columns)

In [48]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [49]:
a3.size

8

In [50]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [51]:
a2.size

12

# 4.item size
- memory occupid by the item

In [52]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a1.itemsize  # integer 64 takes=8bytes

8

In [55]:
a1.dtype='int32'

In [56]:
a1.dtype

dtype('int32')

In [57]:
a1.itemsize # integer 32 takes = 4 byte of memory

4

# 5.dtype
- gives the datatype of the item

In [60]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


# changing data type

# astype

In [61]:
x=np.array([21,1,2,12.3])
x

array([21. ,  1. ,  2. , 12.3])

In [65]:
x.astype(int,copy=True)

array([21,  1,  2, 12])

# Array Operations

In [69]:
z1=np.arange(12).reshape(3,4)
z2=np.arange(12,24).reshape(3,4)

In [71]:
print('z1',z1)
print('z2',z2)

z1 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
z2 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


# scaler opeartions
- Scalar operations on Numpy arrays include performing addition or subtraction or multiplication on each element of a numpy array

# arithmetic

In [72]:
# addition
z1+2 # add 2 on each element

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [73]:
# subtraction
z1-2 # subtract 2  from each element

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [74]:
# multiplication
z1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [75]:
# power
z1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [76]:
# modulo
z1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

# relational Operators
- the relational operators are also known as comparison operators , their main functions is to return a true or false based on the value of operands

In [77]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [78]:
z2>2 # checking for each item

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [79]:
z2<20 #checking for each items

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

# Vector Operations
- We can apply on both numpy array

In [80]:
z1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [82]:
# Arithmatic
z1+z2 # add pair items ,shape is same 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [83]:
z1-z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [84]:
z2*z1

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [85]:
z1/z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

# Array Functions