# Numpy:
 - Numpy is the fundamental package for scientific computing in Python.
    


                                  

# creatig Numpy array

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,321,3,121,32,1]) #1D array

array([  1,   2,   3, 321,   3, 121,  32,   1])

In [4]:
a=np.array([2,3,4,21,131,32]) #vector
print(a)

[  2   3   4  21 131  32]


In [5]:
type(a) 

numpy.ndarray

In [6]:
# 2D array (matrix)
new=np.array([[34,131,21,11],[2,31,12,11]])
print(new)

[[ 34 131  21  11]
 [  2  31  12  11]]


In [7]:
# 3D array (Tensor)
np.array([[1,2,3,1],(1,2,13,1),{1,2,31,12},[1,23,4,4]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

# Array only accept homogenous data type

In [13]:
# 3D array (Tensor)
# np.array({1,2,'r'}) 
np.array([[1,2,3,3],[12,23,13,13],[221,213,123,3211],[121,2212,233,223]])

array([[   1,    2,    3,    3],
       [  12,   23,   13,   13],
       [ 221,  213,  123, 3211],
       [ 121, 2212,  233,  223]])

In [15]:
print(np.array([[1,2,3,3],[12,23,13,13],[221,213,123,3211],[121,2212,'233',223]]))# if i give atleast on estring larg it convert all array into str
np.array([[1,2,3,3],[12,23,13,13],[221,True,123,3211],[121,2212,233,223]]) #if i give bolean value it convert int decimal

[['1' '2' '3' '3']
 ['12' '23' '13' '13']
 ['221' '213' '123' '3211']
 ['121' '2212' '233' '223']]


array([[   1,    2,    3,    3],
       [  12,   23,   13,   13],
       [ 221,    1,  123, 3211],
       [ 121, 2212,  233,  223]])

# dtype
- the desired data -type for the array .if not given then the type will be determined a minimum type required to hold the objects in the sequence

In [16]:
np.array([11,23,12],dtype=float) #float array

array([11., 23., 12.])

In [17]:
np.array([11,232,11,0],dtype=bool) # the boolean values of decimal

array([ True,  True,  True, False])

In [18]:
np.array([11,23,122],dtype=complex) #comlex array with adding j 

array([ 11.+0.j,  23.+0.j, 122.+0.j])

# Numpy Array Vs Python Sequences
- Numpy arrays have a fixed size at creation ,unlike python lists(which can grow dynamically).
changing the size of an ndarray will create a new array and delete the original.

- The elements in a Numpy array are all required to be of the same data type and thus will be the same size in memory

- Numpy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically ,such operations are executed more efficiently and with less code than is possible using Python's built-in sequences.

- A growing plethora of scientific and mathematical Python -based packages ara using Numpy arrays; though these typiocally supports python -sequence input, they convert such input to Numpy arrays prior to processing and they often output Numpy arrays.

# Arange()
- arange can be called with a varying number of positional arguments

In [19]:
np.arange(1,25) # 1 included, 25- last on got excluded

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [20]:
np.arange(1,25,2) # strides--> Alternate numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

# Reshape()
- Both of number products should be equal to number of items present inside the array

In [22]:
np.arange(1,11).reshape(5,2) # first arg is rows 5 second arg columns 2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [23]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Ones & zeros()
- you can initialize the values and create value . ex: in deep learning weight shape

In [26]:
np.ones(3)

array([1., 1., 1.])

In [27]:
np.ones(2,3) # for matrix from method you have to apply 2 tuples

TypeError: Cannot interpret '3' as a data type

In [29]:
np.ones([3,2]),np.ones((3,3))

(array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [31]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# random()
- Return random floats in the half-open interval [0.0, 1.0).

In [32]:
# Another type -->random()
 
np.random.random((4,4))

array([[0.36653438, 0.82688001, 0.14020036, 0.518724  ],
       [0.38233893, 0.62426702, 0.91270586, 0.82432847],
       [0.7414424 , 0.88186798, 0.94110726, 0.92189975],
       [0.45688219, 0.07479453, 0.98247296, 0.7455977 ]])

# linspace()
- It is also called as Linearly space, Linearly seperable in a given range at equal distance it creates points.

In [33]:
np.linspace(-10,10,10) # divide into 10 equal parts

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [35]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

# identity()
- Identity matrix is that diagonal items will be ones and apart from that will be zeros

In [36]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(4) # eye is shortcut

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# Array Attributes
- attributes are the built-in properties of arrays and modules that give you information about their structure or behavior. For arrays (numpy.ndarray).


In [39]:
a1=np.arange(10) # 1D
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a2=np.arange(12,dtype=float).reshape(3,4) # Matrix
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [41]:
a3=np.arange(8).reshape(2,2,2) # 3D -->Tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

 # 1. ndim
 - To findout given arrays numbers of dimensions.

In [42]:
a1.ndim

1

In [43]:
a2.ndim

2

In [44]:
a3.ndim

3

# 2.shape
- gives each item consist of no of rows and no of column

In [45]:
a1.shape #1D array has 10 items

(10,)

In [46]:
a2.shape # 3 rows and 4 columns

(3, 4)

In [47]:
a3.shape

(2, 2, 2)

# 3.size
- gives number of items (rows*columns)

In [48]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [49]:
a3.size

8

In [50]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [51]:
a2.size

12

# 4.item size
- memory occupid by the item

In [52]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a1.itemsize  # integer 64 takes=8bytes

8

In [55]:
a1.dtype='int32'

In [56]:
a1.dtype

dtype('int32')

In [57]:
a1.itemsize # integer 32 takes = 4 byte of memory

4

# 5.dtype
- gives the datatype of the item

In [60]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


# changing data type

# astype

In [61]:
x=np.array([21,1,2,12.3])
x

array([21. ,  1. ,  2. , 12.3])

In [65]:
x.astype(int,copy=True)

array([21,  1,  2, 12])

# Array Operations

In [69]:
z1=np.arange(12).reshape(3,4)
z2=np.arange(12,24).reshape(3,4)

In [71]:
print('z1',z1)
print('z2',z2)

z1 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
z2 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


# scaler opeartions
- Scalar operations on Numpy arrays include performing addition or subtraction or multiplication on each element of a numpy array

# arithmetic

In [72]:
# addition
z1+2 # add 2 on each element

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [73]:
# subtraction
z1-2 # subtract 2  from each element

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [74]:
# multiplication
z1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [75]:
# power
z1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [76]:
# modulo
z1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

# relational Operators
- the relational operators are also known as comparison operators , their main functions is to return a true or false based on the value of operands

In [77]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [78]:
z2>2 # checking for each item

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [79]:
z2<20 #checking for each items

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

# Vector Operations
- We can apply on both numpy array

In [80]:
z1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [82]:
# Arithmatic
z1+z2 # add pair items ,shape is same 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [83]:
z1-z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [84]:
z2*z1

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [85]:
z1/z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

# Array Functions
- in numpy axis
- axis=0 ->column
- axis=1 ->row

In [3]:
k1=np.random.random((3,3))
k1=np.round(k1*100)
k1

array([[79., 79., 67.],
       [18., 28., 26.],
       [44., 51., 47.]])

In [6]:
# max
np.max(k1)

np.float64(79.0)

In [7]:
# min
np.min(k1)

np.float64(18.0)

In [8]:
# sum
np.sum(k1)

np.float64(439.0)

In [9]:
# product
np.prod(k1)

np.float64(577901178638784.0)

In [10]:
# if we wanna maximum of every row
np.max(k1,axis=1)

array([79., 28., 51.])

In [11]:
# maximum of every column
np.max(k1,axis=0)

array([79., 79., 67.])

In [12]:
# product of every column
np.prod(k1,axis=0)

array([ 62568., 112812.,  81874.])

# Statistic related functions

In [14]:
# mean
k1

array([[79., 79., 67.],
       [18., 28., 26.],
       [44., 51., 47.]])

In [15]:
np.mean(k1)

np.float64(48.77777777777778)

In [16]:
# mean of every column
np.mean(k1,axis=0)

array([47.        , 52.66666667, 46.66666667])

In [17]:
# median
np.median(k1)

np.float64(47.0)

In [18]:
# median of every row
np.median(k1,axis=1)

array([79., 26., 47.])

In [19]:
# standard deviation
np.std(k1)

np.float64(21.311331246690642)

In [20]:
np.std(k1,axis=0) #std of columns

array([24.99333244, 20.85398976, 16.73983937])

In [21]:
# variance
np.var(k1)

np.float64(454.17283950617286)

# Trignomentory Functions

In [22]:
k1

array([[79., 79., 67.],
       [18., 28., 26.],
       [44., 51., 47.]])

In [23]:
# sin
np.sin(k1)

array([[-0.44411267, -0.44411267, -0.85551998],
       [-0.75098725,  0.27090579,  0.76255845],
       [ 0.01770193,  0.67022918,  0.12357312]])

In [24]:
np.cos(k1)

array([[-0.89597095, -0.89597095, -0.5177698 ],
       [ 0.66031671, -0.96260587,  0.64691932],
       [ 0.99984331,  0.7421542 , -0.99233547]])

In [25]:
np.tan(k1)

array([[ 0.49567753,  0.49567753,  1.65231726],
       [-1.13731371, -0.2814296 ,  1.17875355],
       [ 0.0177047 ,  0.90308615, -0.12452757]])

# dot product
- the numpy module of Python a function to perform the dot product of two arrays.

In [35]:
s2=np.arange(12).reshape(3,4)
s3=np.arange(12,24).reshape(3,4)
s4=np.arange(12,24).reshape(4,3)

In [33]:
print(s2)
print(s3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [34]:
np.dot(s2,s3)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [36]:
np.dot(s2,s4) #its possible

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

# log and exponents

In [38]:
np.exp(s2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

# round/floor/ceil

# 1.round()
- The numpy.round() function rounds the elements of an array to the nearest integer or to the specified number of decimals.

In [41]:
# round to the nearest integer
arr=np.array([1.2,34.3,12.2,3.7,9.8])
rounded_arr=np.round(arr)
print(rounded_arr)

[ 1. 34. 12.  4. 10.]


In [42]:
# Round to two decimals
arr=np.array([1.234,2.332,13.423])
np.round(arr,decimals=2)

array([ 1.23,  2.33, 13.42])

In [79]:
# rondomly
np.round(np.random.random((2,3))*100)

array([[53.,  3., 85.],
       [80., 18., 77.]])

# floor
- the numpy.floor() function return the smallest integer less than or equal to each element of an array.

In [80]:
# floor operations
arr=np.array([1.2,2.7,3.5,49.3]) # compact the float to lower intiger
floored_arr=np.floor(arr)
print(floored_arr)


[ 1.  2.  3. 49.]


In [82]:
np.floor(np.random.random((2,3))*100)

array([[ 6., 20., 89.],
       [38., 40., 47.]])

# ceil
- The numpy.ceil() function returns the largest integer greater than equal to each element of an array 

In [83]:
arr=np.array([1.2,2.4,3.4,4.9])
ceiled_arr=np.ceil(arr)
print(ceiled_arr)

[2. 3. 4. 5.]


# Indexing And Slicing

In [84]:
p1=np.arange(10)
p2=np.arange(12).reshape(3,4)
p3=np.arange(8).reshape(2,2,2)

In [87]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# indexing on 1D array

In [90]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
# fetching last item
p1[-1]

np.int64(9)

In [92]:
# fetching first item
p1[0]

np.int64(0)

# indexing on 2D array

In [93]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
# fetching desired element:6
p2[1,2] # here 1 is row index ,2 is column index

np.int64(6)

In [95]:
# fetching the ellement:11
p2[2,3]

np.int64(11)

In [97]:
# fetching desired element:4
p2[1,0]

np.int64(4)

# indexing on 3D (Tensors)

In [98]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [104]:
# fetching  desired element:5
print('first',p3[1])
print('then',p3[1,0])
print('and',p3[1,0,1] )

first [[4 5]
 [6 7]]
then [4 5]
and 5


# EXPLANATION :
- Here 3D is consists of 2 ,2D array , so Firstly we take 1 because our desired is 5 is in second matrix which is 1 .and 1 row so 0 and second column so 1 

In [105]:
# fetching desired :0
p3[0,0,0]

np.int64(0)

In [107]:
# fetching desred 6:
p3[1,1,0]

np.int64(6)

# Slicing
- Fetching Multiple items

# Slicing on 1D Array
- remember slicing work on n-1 basis

In [108]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
# fetching the desired element 2,3,4
p1[2:5]

array([2, 3, 4])

In [110]:
# Alternate (same as python)
p1[::2]

array([0, 2, 4, 6, 8])

In [111]:
p1[2:5:2]

array([2, 4])

# Slicing on 2D Array

In [112]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
# fetching total first row
p2[0,:]

array([0, 1, 2, 3])

In [115]:
# fetching total third column
p2[:,2]

array([ 2,  6, 10])

In [116]:
# fetching 5,6,9,10
p2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [117]:
# fetch 0,3 and 8,11
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
p2[0::2,0::3] #step slicing

array([[ 0,  3],
       [ 8, 11]])

In [119]:
# fetch 1,3 and 9,11
p2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [120]:
# fetch only 4,7
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
p2[1,0::3]

array([4, 7])

In [123]:
p2[1] # 1 index row

array([4, 5, 6, 7])

In [124]:
p2[:,2] # 2 index column

array([ 2,  6, 10])

In [125]:
# fetch 1,2,3 and 5,6,7
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
p2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [128]:
# fetch 1,3 and 5,7
p2[:2,1::2]

array([[1, 3],
       [5, 7]])

EXPLANATION : 0:2 selects the rows from index 0 (inclusive) to index 2 (exclusive), which 
means it will select the first and second rows of the array. , is used to separate row and column 
selections. 1::2 selects the columns starting from index 1 and selects every second column. So 
it will select the second and fourth columns of the array.

In [129]:
# Slicing in 3D
p3=np.arange(27).reshape(3,3,3)

In [130]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [131]:
# fetch the second matrix
p3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [132]:
# fetch the first and last
p3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [133]:
# Fetch  1d array's 2 row -->3,4,5
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [135]:
p3[0,1,:]

array([3, 4, 5])

In [136]:
# fetch numpy array middle column -->10,13,16
p3[1,:,1]

array([10, 13, 16])

In [137]:
# fetch 2D array--> 22,23,25,26
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [138]:
p3[2,1:,1:]

array([[22, 23],
       [25, 26]])

EXPLANATION : Here we go through 3 stages , where 2 for last array , and (1:) from second 
row to total rows , and (1:) is for second column to total columns

In [139]:
# fetch 0,2,18,20
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [140]:
p3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [141]:
p3[::2,0] # it fetches the rows of matrix

array([[ 0,  1,  2],
       [18, 19, 20]])

In [142]:
p3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

EXPLANATION : Here we take (0::2) first adn last column , so we did jump using this, and we 
took (0) for first row , and we (::2) ignored middle column 

# Iterating

In [143]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
# looping on 1D array
for i in p1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [145]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [146]:
# looping in 2D array
for i in p2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [147]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [148]:
# looping in 3d array
for i in p3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


print all items in 3D using nditer ---- > first convert in to 1D and applying Loop 

In [149]:
for i in np.nditer(p3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

# Transpose
- Converts rows in to columns and column into rows

In [150]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [151]:
# method 1
p2.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [152]:
# method2
np.transpose(p2) 

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [153]:
# method 3
p2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [154]:
p3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

# Ravel
- Converting any array int 1D array

In [156]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [157]:
np.ravel(p2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [158]:
p2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [159]:
p3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking
- Stacking is the concept of joining in Numpy. arrays having the same dimensions can be stacked.

# Horizontal Stacking

In [161]:
w1=np.arange(12).reshape(3,4)
w2=np.arange(12,24).reshape(3,4) # dimension should be same

In [162]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [163]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [165]:
# using hstack for horizonatal stacking
np.hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [166]:
w2.hstack(w1)

AttributeError: 'numpy.ndarray' object has no attribute 'hstack'

# Vertical Stacking

In [167]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [168]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [169]:
# using vstack for vertical stacking
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting
- Its opposite of stacking 
- it's splits array 

In [170]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Horizonatal Splitting

In [171]:
np.hsplit(w1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [172]:
np.hsplit(w1,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

# Vertical Splitting

In [173]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [175]:
np.vsplit(w2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [177]:
np.vsplit(w2) # need to give the how many arrays we want

TypeError: vsplit() missing 1 required positional argument: 'indices_or_sections'