# Support Vector Regression 
- Support Vector Regression is a supervised machine learning algorithm that predicts continuous values by fitting a function within a predefined error margin called epsilon while minimizing model complexity.

- formula

        -a<y=wx+b<+a
# Hyperplane

- The regression line that predicts the output.
 y=wx+b

# Support Vectors

- These are the data points closest to the boundary of the ε tube.

- They determine the position of the regression line.

- That is why they are called support vectors.

# Kernel Trick

- If data is not linear, SVR uses kernels to convert data to higher dimensions.

  - common kernels

     - Linear (linear data)
     - Polynomial (polynomial relationship)
     - RBF-Radial basis function (Non-linear complex data)
     - Sigmoid (neural network like)

# Important Parameters in SVR
- C (Regularization Parameter)

- Controls penalty for errors.

    Small C
    → larger margin
    → more errors allowed

    Large C
    → tries to fit data tightly
    → risk of overfitting


# ε (Epsilon)

- Defines acceptable error margin.

    Small ε
    → model tries to fit more points
    
    Large ε
    → smoother model

- Epsilon (ε)

- It defines the margin of tolerance.

Example:
    
    If ε = 1, prediction errors within ±1 are ignored.
    
    So SVR does not try to fit every point exactly.

# 7️⃣ Advantages

✔ Works well for high dimensional data

✔ Handles non-linear relationships

✔ Robust to outliers

# 8️⃣ Disadvantages

❌ Slow for large datasets

❌ Hard to choose best kernel and parameters

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data=pd.DataFrame({
    'cgpa':[5,5.6,8,9,6.5,7.8,9,4.5,8.6],
    'package':[4,8,9,7,3,15,3,12,9]
})

In [4]:
data

,cgpa,package
0,5.0,4
1,5.6,8
2,8.0,9
3,9.0,7
4,6.5,3
5,7.8,15
6,9.0,3
7,4.5,12
8,8.6,9


In [42]:
from sklearn.svm import SVR
svr=SVR(degree=5,kernel='poly')

In [43]:
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [44]:
svr.fit(X,y)

,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm.If none is given, 'rbf' will be used. If a callable is given it isused to precompute the kernel matrix.For an intuitive visualization of different kernel typessee :ref:`sphx_glr_auto_examples_svm_plot_svm_regression.py`",'poly'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",5
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive.The penalty is a squared l2. For an intuitive visualization of theeffects of scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"epsilon epsilon: float, default=0.1Epsilon in the epsilon-SVR model. It specifies the epsilon-tubewithin which no penalty is associated in the training loss functionwith points predicted within a distance epsilon from the actualvalue. Must be non-negative.",0.1
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide `.",True
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False
,"max_iter max_iter: int, default=-1Hard limit on iterations within solver, or -1 for no limit.",-1


In [45]:
y_pred=svr.predict([[9]])
y_pred

array([6.53645246])

In [46]:
# this model is not giving a good output for this dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("E:\data\data_set\emp_sal.csv")
X=df.iloc[:,1:2].values
y=df.iloc[:,2].values

In [2]:

from sklearn.svm import SVR
from sklearn.metrics import r2_score
svr_reg=SVR(kernel='poly',gamma='scale',degree=5,coef0=3,epsilon=2)
svr_reg.fit(X,y)

svr_pred=svr_reg.predict([[6.5]])
svr_pred
r2_score(svr_pred,y)

array([180902.48648217])

# KNN-Regressor
- KNN Regressor is a supervised machine learning algorithm used for regression problems (predicting continuous values like price, temperature, sales, etc.).

- Instead of learning a mathematical model, it predicts the output based on the nearest data points in the dataset.

- Simple Idea

- KNN Regressor predicts the value of a new data point by taking the average of the K nearest data points.

# 1️⃣ How KNN Regression Works

- Steps:

    1.Choose a value for K (number of neighbors).
    
    2. Calculate the distance between the new data point and all training data points.
    
    3. Select the K nearest points.
    
    4. Take the average of their target values.
    
    5. That average becomes the predicted value.

# 2️⃣ Distance Metrics

- KNN uses distance to find neighbors.

- Common distances:

    - Euclidean Distance (Most Used)

    d=sqrt((x1-x2)**2+(y1-y2)**2)

     - Manhattan Distance

     d=abs(x1-x2)+abs(y1-y2)

# 3️⃣ Important Parameters
- 1️⃣ n_neighbors (K)

- Number of neighbors used for prediction.
    - Small K → sensitive to noise
    - Large K → smoother predictions

- 2️⃣ weights

- How neighbors influence prediction.

   - uniform
    
    All neighbors have equal importance.
    
   - distance
    
    Closer neighbors have more influence.


# 5️⃣ When to Use KNN Regression

- Use when:

  -  Dataset is small
    
  -  Data pattern is non-linear
    
  -  No assumption about data distribution

# 6️⃣ Advantages

    ✔ Simple algorithm
    ✔ No training phase
    ✔ Works well with non-linear data

# 7️⃣ Disadvantages
    
    ❌ Slow for large datasets
    ❌ Sensitive to feature scaling
    ❌ Requires storing full dataset
    
# 8️⃣ Important Note (Very Important in Interviews)

- Feature Scaling is required for KNN because distance calculations are affected by -feature magnitude.

- Example scaling methods:

    Standardization
    
    MinMaxScaler

- KNN Regressor is a non-parametric supervised learning algorithm that predicts continuous values by averaging the target values of the K nearest data points based on a distance metric.

# knn-regressor code

In [3]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor(n_neighbors=4,weights='distance',algorithm='ball_tree')
knn.fit(X,y)

knn_pred=knn.predict([[6.5]])
knn_pred

array([182500.])

In [4]:
from sklearn.metrics import r2_score

In [5]:
knn_pred=knn.predict(X)

In [7]:
score=r2_score(y,knn_pred)
score

1.0